package io.github.aughtone.types.units

import kotlin.test.Test
import kotlin.test.assertTrue

class UnitOfMeasureTest {
    private val historicValues = listOf(
        "Acre",
        "AcreFoot",
        "Ampere",
        "ArcMinute",
        "ArcSecond",
        "AstronomicalUnit",
        "Bit",
        "Bushel",
        "Byte",
        "Calorie",
        "Carat",
        "Celsius",
        "Centiliter",
        "Centimeter",
        "CubicCentimeter",
        "CubicFoot",
        "CubicInch",
        "CubicKilometer",
        "CubicMeter",
        "CubicMile",
        "CubicYard",
        "Decameter",
        "Cup",
        "Deciliter",
        "Decimeter",
        "Degree",
        "Fahrenheit",
        "Fathom",
        "FluidOunce",
        "FoodCalorie",
        "Foot",
        "Furlong",
        "Gallon",
        "GallonImperial",
        "Gigabit",
        "Gigabyte",
        "Gigahertz",
        "Gigawatt",
        "Gram",
        "GForce",
        "Hectare",
        "Hectoliter",
        "Hectopascal",
        "Hertz",
        "Horsepower",
        "Inch",
        "InchHg",
        "Joule",
        "Karat",
        "Kelvin",
        "Kilobit",
        "Kilobyte",
        "Kilocalorie",
        "Kilogram",
        "Kilohertz",
        "Kilojoule",
        "Kilometer",
        "KilometerPerHour",
        "Kilowatt",
        "KilowattHour",
        "LightYear",
        "Liter",
        "LiterPerKilometer",
        "LiterPer100Kilometers",
        "Lux",
        "Megabit",
        "Megabyte",
        "Megahertz",
        "Megaliter",
        "Megawatt",
        "Meter",
        "MeterPerSecond",
        "MeterPerSecondSquared",
        "MetricTon",
        "Microgram",
        "Micrometer",
        "Microsecond",
        "Mile",
        "MilePerGallon",
        "MilePerHour",
        "Milliampere",
        "Millibar",
        "Milligram",
        "Milliliter",
        "Millimeter",
        "MillimeterOfMercury",
        "Millisecond",
        "Milliwatt",
        "Nanometer",
        "Nanosecond",
        "NauticalMile",
        "Ohm",
        "Ounce",
        "OunceTroy",
        "Parsec",
        "Picometer",
        "Pint",
        "Pound",
        "PoundPerSquareInch",
        "Quart",
        "Radian",
        "SquareCentimeter",
        "SquareFoot",
        "SquareInch",
        "SquareKilometer",
        "SquareMeter",
        "SquareMile",
        "SquareYard",
        "Stone",
        "Tablespoon",
        "Teaspoon",
        "Terabit",
        "Terabyte",
        "Ton",
        "Volt",
        "Watt",
        "Yard",
        "Day",
        "Hour",
        "Minute",
        "Second",
        "Month",
        "Week",
        "Year",
        "YearJulian"
    )

    @Test
    fun `retains historic enum name`() {
        // All the enum values that may be used in the
        // database or on remote systems must be retained.
        assertTrue(
            UnitOfMeasure.entries.map { it.name }
                .containsAll(historicValues),
            "Missing historic names for the enum."
        )
    }

    @Test
    fun `doesnt have unchecked new values`() {
        // Adding a new value without ensuring it doesn't change
        // may introduce a bug, if it is later removed or renamed.
        assertTrue(
            historicValues.containsAll(UnitOfMeasure.entries.map { it.name }),
            "There are new unchecked values for the enum."
        )
    }
}
