package io.github.aughtone.types.units

import kotlin.test.Test
import kotlin.test.assertTrue

class UnitOfMeasureTest {
    private val historicValues = listOf(
        "ACRE",
        "ACRE_FOOT",
        "AMPERE",
        "ARC_MINUTE",
        "ARC_SECOND",
        "ASTRONOMICAL_UNIT",
        "BIT",
        "BUSHEL",
        "BYTE",
        "CALORIE",
        "CARAT",
        "CELSIUS",
        "CENTILITER",
        "CENTIMETER",
        "CUBIC_CENTIMETER",
        "CUBIC_FOOT",
        "CUBIC_INCH",
        "CUBIC_KILOMETER",
        "CUBIC_METER",
        "CUBIC_MILE",
        "CUBIC_YARD",
        "DECAMETER",
        "CUP",
        "DECILITER",
        "DECIMETER",
        "DEGREE",
        "FAHRENHEIT",
        "FATHOM",
        "FLUID_OUNCE",
        "FOODCALORIE",
        "FOOT",
        "FURLONG",
        "GALLON",
        "GALLON_IMPERIAL",
        "GIGABIT",
        "GIGABYTE",
        "GIGAHERTZ",
        "GIGAWATT",
        "GRAM",
        "G_FORCE",
        "HECTARE",
        "HECTOLITER",
        "HECTOPASCAL",
        "HERTZ",
        "HORSEPOWER",
        "INCH",
        "INCH_HG",
        "JOULE",
        "KARAT",
        "KELVIN",
        "KILOBIT",
        "KILOBYTE",
        "KILOCALORIE",
        "KILOGRAM",
        "KILOHERTZ",
        "KILOJOULE",
        "KILOMETER",
        "KILOMETER_PER_HOUR",
        "KILOWATT",
        "KILOWATT_HOUR",
        "LIGHT_YEAR",
        "LITER",
        "LITER_PER_KILOMETER",
        "LITER_PER_100KILOMETERS",
        "LUX",
        "MEGABIT",
        "MEGABYTE",
        "MEGAHERTZ",
        "MEGALITER",
        "MEGAWATT",
        "METER",
        "METER_PER_SECOND",
        "METER_PER_SECOND_SQUARED",
        "METRIC_TON",
        "MICROGRAM",
        "MICROMETER",
        "MICROSECOND",
        "MILE",
        "MILE_PER_GALLON",
        "MILE_PER_HOUR",
        "MILLIAMPERE",
        "MILLIBAR",
        "MILLIGRAM",
        "MILLILITER",
        "MILLIMETER",
        "MILLIMETER_OF_MERCURY",
        "MILLISECOND",
        "MILLIWATT",
        "NANOMETER",
        "NANOSECOND",
        "NAUTICAL_MILE",
        "OHM",
        "OUNCE",
        "OUNCE_TROY",
        "PARSEC",
        "PICOMETER",
        "PINT",
        "POUND",
        "POUND_PER_SQUARE_INCH",
        "QUART",
        "RADIAN",
        "SQUARE_CENTIMETER",
        "SQUARE_FOOT",
        "SQUARE_INCH",
        "SQUARE_KILOMETER",
        "SQUARE_METER",
        "SQUARE_MILE",
        "SQUARE_YARD",
        "STONE",
        "TABLESPOON",
        "TEASPOON",
        "TERABIT",
        "TERABYTE",
        "TON",
        "VOLT",
        "WATT",
        "YARD",
        "DAY",
        "HOUR",
        "MINUTE",
        "SECOND",
        "MONTH",
        "WEEK",
        "YEAR",
        "YEAR_JULIAN"
    )

    @Test
    fun `retains historic enum name`() {
        // All the enum values that may be used in the
        // database or on remote systems must be retained.
        assertTrue(
            UnitOfMeasure.entries.map { it.name }
                .containsAll(historicValues),
            "Missing historic names for the enum."
        )
    }

    @Test
    fun `doesnt have unchecked new values`() {
        // Adding a new value without ensuring it doesn't change
        // may introduce a bug, if it is later removed or renamed.
        assertTrue(
            historicValues.containsAll(UnitOfMeasure.entries.map { it.name }),
            "There are new unchecked values for the enum."
        )
    }
}
