[versions]
namespace = "io.github.aughtone.types"
group = "io.github.aughtone"
versionName = "3.1.0"
android-minSdk = "17"
android-compileSdk = "37"

agp = "9.2.1"
kotlin = "2.4.0"
kotlinx-serialization = "1.11.0"
kotlinx-datetime = "0.8.0"
vanniktech = "0.37.0"
kotlinBrowser = "2026.7.1"
ionspin-bignum ="0.3.10"

[libraries]
kotlin-browser = { module = "org.jetbrains.kotlin-wrappers:kotlin-browser", version.ref = "kotlinBrowser" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

bignum = { module = "com.ionspin.kotlin:bignum", version.ref = "ionspin-bignum" }

[plugins]
multiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech" }
