package io.github.aughtone.types.financial

import io.github.aughtone.types.util.lazyMapOf

/**
 * Data Source: https://www.iso.org/iso-4217-currency-codes.html
 *
 * This map is meant to supplement curency information on platforms that don't normally contain it.
 *
 * A map containing currency data, keyed by the three-letter ISO 4217 currency code.
 * Each entry's value is a lambda that returns a [Currency] object, which
 * contains the currency's display name and numeric code.
 *
 * This map is lazily initialized using [lazyMapOf], meaning the values are
 * computed only when they are first accessed.
 *
 * The map does not contain any entries for special codes like precious metals, testing, or No currency involved.
 *
 * @see Currency
 * @see lazyMapOf
 */

internal val currencyResourceMap: Map<String, Currency> = mapOf(
    "AED" to lazy { Currency("AED", 784, 2, "UAE Dirham", listOf("United Arab Emirates (The)"), "د.إ") },
    "AFN" to lazy { Currency("AFN", 971, 2, "Afghani", listOf("Afghanistan"), "؋") },
    "ALL" to lazy { Currency("ALL", 8, 2, "Lek", listOf("Albania"), "L") },
    "AMD" to lazy { Currency("AMD", 51, 2, "Armenian Dram", listOf("Armenia"), "֏") },
    "ANG" to lazy { Currency("ANG", 532, 2, "Netherlands Antillean Guilder", listOf("Curaçao", "Sint Maarten (Dutch Part)"), "ƒ") },
    "AOA" to lazy { Currency("AOA", 973, 2, "Kwanza", listOf("Angola"), "Kz") },
    "ARS" to lazy { Currency("ARS", 32, 2, "Argentine Peso", listOf("Argentina"), "$") },
    "AUD" to lazy { Currency("AUD", 36, 2, "Australian Dollar", listOf("Australia", "Christmas Island", "Cocos (Keeling) Islands (The)", "Heard Island and Mcdonald Islands", "Kiribati", "Nauru", "Norfolk Island", "Tuvalu"), "$") },
    "AWG" to lazy { Currency("AWG", 533, 2, "Aruban Florin", listOf("Aruba"), "ƒ") },
    "AZN" to lazy { Currency("AZN", 944, 2, "Azerbaijan Manat", listOf("Azerbaijan"), "₼") },
    "BAM" to lazy { Currency("BAM", 977, 2, "Convertible Mark", listOf("Bosnia and Herzegovina"), "KM") },
    "BBD" to lazy { Currency("BBD", 52, 2, "Barbados Dollar", listOf("Barbados"), "$") },
    "BDT" to lazy { Currency("BDT", 50, 2, "Taka", listOf("Bangladesh"), "৳") },
    "BGN" to lazy { Currency("BGN", 975, 2, "Bulgarian Lev", listOf("Bulgaria"), "лв") },
    "BHD" to lazy { Currency("BHD", 48, 3, "Bahraini Dinar", listOf("Bahrain"), ".د.ب") },
    "BIF" to lazy { Currency("BIF", 108, 0, "Burundi Franc", listOf("Burundi"), "FBu") },
    "BMD" to lazy { Currency("BMD", 60, 2, "Bermudian Dollar", listOf("Bermuda"), "$") },
    "BND" to lazy { Currency("BND", 96, 2, "Brunei Dollar", listOf("Brunei Darussalam"), "$") },
    "BOB" to lazy { Currency("BOB", 68, 2, "Boliviano", listOf("Bolivia (Plurinational State Of)"), "\$b") },
    "BOV" to lazy { Currency("BOV", 984, 2, "Mvdol", listOf("Bolivia (Plurinational State Of)"), "BOV") },
    "BRL" to lazy { Currency("BRL", 986, 2, "Brazilian Real", listOf("Brazil"), "R$") },
    "BSD" to lazy { Currency("BSD", 44, 2, "Bahamian Dollar", listOf("Bahamas (The)"), "$") },
    "BTN" to lazy { Currency("BTN", 64, 2, "Ngultrum", listOf("Bhutan"), "Nu.") },
    "BWP" to lazy { Currency("BWP", 72, 2, "Pula", listOf("Botswana"), "P") },
    "BYN" to lazy { Currency("BYN", 933, 2, "Belarusian Ruble", listOf("Belarus"), "Br") },
    "BZD" to lazy { Currency("BZD", 84, 2, "Belize Dollar", listOf("Belize"), "BZ$") },
    "CAD" to lazy { Currency("CAD", 124, 2, "Canadian Dollar", listOf("Canada"), "$") },
    "CDF" to lazy { Currency("CDF", 976, 2, "Congolese Franc", listOf("Congo (The Democratic Republic of The)"), "FC") },
    "CHE" to lazy { Currency("CHE", 947, 2, "WIR Euro", listOf("Switzerland"), "CHE") },
    "CHF" to lazy { Currency("CHF", 756, 2, "Swiss Franc", listOf("Liechtenstein", "Switzerland"), "CHF") },
    "CHW" to lazy { Currency("CHW", 948, 2, "WIR Franc", listOf("Switzerland"), "CHW") },
    "CLF" to lazy { Currency("CLF", 990, 4, "Unidad de Fomento", listOf("Chile"), "CLF") },
    "CLP" to lazy { Currency("CLP", 152, 0, "Chilean Peso", listOf("Chile"), "$") },
    "CNY" to lazy { Currency("CNY", 156, 2, "Yuan Renminbi", listOf("China"), "¥") },
    "COP" to lazy { Currency("COP", 170, 2, "Colombian Peso", listOf("Colombia"), "$") },
    "COU" to lazy { Currency("COU", 970, 2, "Unidad de Valor Real", listOf("Colombia"), "COU") },
    "CRC" to lazy { Currency("CRC", 188, 2, "Costa Rican Colon", listOf("Costa Rica"), "₡") },
    "CUC" to lazy { Currency("CUC", 931, 2, "Peso Convertible", listOf("Cuba"), "$") },
    "CUP" to lazy { Currency("CUP", 192, 2, "Cuban Peso", listOf("Cuba"), "₱") },
    "CVE" to lazy { Currency("CVE", 132, 2, "Cabo Verde Escudo", listOf("Cabo Verde"), "$") },
    "CZK" to lazy { Currency("CZK", 203, 2, "Czech Koruna", listOf("Czechia"), "Kč") },
    "DJF" to lazy { Currency("DJF", 262, 0, "Djibouti Franc", listOf("Djibouti"), "Fdj") },
    "DKK" to lazy { Currency("DKK", 208, 2, "Danish Krone", listOf("Denmark", "Faroe Islands (The)", "Greenland"), "kr") },
    "DOP" to lazy { Currency("DOP", 214, 2, "Dominican Peso", listOf("Dominican Republic (The)"), "RD$") },
    "DZD" to lazy { Currency("DZD", 12, 2, "Algerian Dinar", listOf("Algeria"), "دج") },
    "EGP" to lazy { Currency("EGP", 818, 2, "Egyptian Pound", listOf("Egypt"), "£") },
    "ERN" to lazy { Currency("ERN", 232, 2, "Nakfa", listOf("Eritrea"), "Nfk") },
    "ETB" to lazy { Currency("ETB", 230, 2, "Ethiopian Birr", listOf("Ethiopia"), "Br") },
    "EUR" to lazy { Currency("EUR", 978, 2, "Euro", listOf("Åland Islands", "Andorra", "Austria", "Belgium", "Croatia", "Cyprus", "Estonia", "European Union", "Finland", "France", "French Guiana", "French Southern Territories (The)", "Germany", "Greece", "Guadeloupe", "Holy See (The)", "Ireland", "Italy", "Latvia", "Lithuania", "Luxembourg", "Malta", "Martinique", "Mayotte", "Monaco", "Montenegro", "Netherlands (The)", "Portugal", "Réunion", "Saint Barthélemy", "Saint Martin (French Part)", "Saint Pierre and Miquelon", "San Marino", "Slovakia", "Slovenia", "Spain"), "€") },
    "FJD" to lazy { Currency("FJD", 242, 2, "Fiji Dollar", listOf("Fiji"), "$") },
    "FKP" to lazy { Currency("FKP", 238, 2, "Falkland Islands Pound", listOf("Falkland Islands (The) [Malvinas]"), "£") },
    "GBP" to lazy { Currency("GBP", 826, 2, "Pound Sterling", listOf("Guernsey", "Isle of Man", "Jersey", "United Kingdom of Great Britain and Northern Ireland (The)"), "£") },
    "GEL" to lazy { Currency("GEL", 981, 2, "Lari", listOf("Georgia"), "₾") },
    "GHS" to lazy { Currency("GHS", 936, 2, "Ghana Cedi", listOf("Ghana"), "GH₵") },
    "GIP" to lazy { Currency("GIP", 292, 2, "Gibraltar Pound", listOf("Gibraltar"), "£") },
    "GMD" to lazy { Currency("GMD", 270, 2, "Dalasi", listOf("Gambia (The)"), "D") },
    "GNF" to lazy { Currency("GNF", 324, 0, "Guinean Franc", listOf("Guinea"), "FG") },
    "GTQ" to lazy { Currency("GTQ", 320, 2, "Quetzal", listOf("Guatemala"), "Q") },
    "GYD" to lazy { Currency("GYD", 328, 2, "Guyana Dollar", listOf("Guyana"), "$") },
    "HKD" to lazy { Currency("HKD", 344, 2, "Hong Kong Dollar", listOf("Hong Kong"), "$") },
    "HNL" to lazy { Currency("HNL", 340, 2, "Lempira", listOf("Honduras"), "L") },
    "HTG" to lazy { Currency("HTG", 332, 2, "Gourde", listOf("Haiti"), "G") },
    "HUF" to lazy { Currency("HUF", 348, 2, "Forint", listOf("Hungary"), "Ft") },
    "IDR" to lazy { Currency("IDR", 360, 2, "Rupiah", listOf("Indonesia"), "Rp") },
    "ILS" to lazy { Currency("ILS", 376, 2, "New Israeli Sheqel", listOf("Israel"), "₪") },
    "INR" to lazy { Currency("INR", 356, 2, "Indian Rupee", listOf("Bhutan", "India"), "₹") },
    "IQD" to lazy { Currency("IQD", 368, 3, "Iraqi Dinar", listOf("Iraq"), "ع.د") },
    "IRR" to lazy { Currency("IRR", 364, 2, "Iranian Rial", listOf("Iran (Islamic Republic Of)"), "﷼") },
    "ISK" to lazy { Currency("ISK", 352, 0, "Iceland Krona", listOf("Iceland"), "kr") },
    "JMD" to lazy { Currency("JMD", 388, 2, "Jamaican Dollar", listOf("Jamaica"), "J$") },
    "JOD" to lazy { Currency("JOD", 400, 3, "Jordanian Dinar", listOf("Jordan"), "JD") },
    "JPY" to lazy { Currency("JPY", 392, 0, "Yen", listOf("Japan"), "¥") },
    "KES" to lazy { Currency("KES", 404, 2, "Kenyan Shilling", listOf("Kenya"), "KSh") },
    "KGS" to lazy { Currency("KGS", 417, 2, "Som", listOf("Kyrgyzstan"), "лв") },
    "KHR" to lazy { Currency("KHR", 116, 2, "Riel", listOf("Cambodia"), "៛") },
    "KMF" to lazy { Currency("KMF", 174, 0, "Comorian Franc ", listOf("Comoros (The)"), "CF") },
    "KPW" to lazy { Currency("KPW", 408, 2, "North Korean Won", listOf("Korea (The Democratic People’s Republic Of)"), "₩") },
    "KRW" to lazy { Currency("KRW", 410, 0, "Won", listOf("Korea (The Republic Of)"), "₩") },
    "KWD" to lazy { Currency("KWD", 414, 3, "Kuwaiti Dinar", listOf("Kuwait"), "KD") },
    "KYD" to lazy { Currency("KYD", 136, 2, "Cayman Islands Dollar", listOf("Cayman Islands (The)"), "$") },
    "KZT" to lazy { Currency("KZT", 398, 2, "Tenge", listOf("Kazakhstan"), "₸") },
    "LAK" to lazy { Currency("LAK", 418, 2, "Lao Kip", listOf("Lao People’s Democratic Republic (The)"), "₭") },
    "LBP" to lazy { Currency("LBP", 422, 2, "Lebanese Pound", listOf("Lebanon"), "£") },
    "LKR" to lazy { Currency("LKR", 144, 2, "Sri Lanka Rupee", listOf("Sri Lanka"), "₨") },
    "LRD" to lazy { Currency("LRD", 430, 2, "Liberian Dollar", listOf("Liberia"), "$") },
    "LSL" to lazy { Currency("LSL", 426, 2, "Loti", listOf("Lesotho"), "M") },
    "LYD" to lazy { Currency("LYD", 434, 3, "Libyan Dinar", listOf("Libya"), "LD") },
    "MAD" to lazy { Currency("MAD", 504, 2, "Moroccan Dirham", listOf("Morocco", "Western Sahara"), "MAD") },
    "MDL" to lazy { Currency("MDL", 498, 2, "Moldovan Leu", listOf("Moldova (The Republic Of)"), "lei") },
    "MGA" to lazy { Currency("MGA", 969, 2, "Malagasy Ariary", listOf("Madagascar"), "Ar") },
    "MKD" to lazy { Currency("MKD", 807, 2, "Denar", listOf("North Macedonia"), "ден") },
    "MMK" to lazy { Currency("MMK", 104, 2, "Kyat", listOf("Myanmar"), "K") },
    "MNT" to lazy { Currency("MNT", 496, 2, "Tugrik", listOf("Mongolia"), "₮") },
    "MOP" to lazy { Currency("MOP", 446, 2, "Pataca", listOf("Macao"), "MOP$") },
    "MRU" to lazy { Currency("MRU", 929, 2, "Ouguiya", listOf("Mauritania"), "UM") },
    "MUR" to lazy { Currency("MUR", 480, 2, "Mauritius Rupee", listOf("Mauritius"), "₨") },
    "MVR" to lazy { Currency("MVR", 462, 2, "Rufiyaa", listOf("Maldives"), "Rf") },
    "MWK" to lazy { Currency("MWK", 454, 2, "Malawian Kwacha", listOf("Malawi"), "MK") },
    "MXN" to lazy { Currency("MXN", 484, 2, "Mexican Peso", listOf("Mexico"), "$") },
    "MXV" to lazy { Currency("MXV", 979, 2, "Mexican Unidad de Inversion (UDI)", listOf("Mexico"), "MXV") },
    "MYR" to lazy { Currency("MYR", 458, 2, "Malaysian Ringgit", listOf("Malaysia"), "RM") },
    "MZN" to lazy { Currency("MZN", 943, 2, "Mozambique Metical", listOf("Mozambique"), "MT") },
    "NAD" to lazy { Currency("NAD", 516, 2, "Namibia Dollar", listOf("Namibia"), "$") },
    "NGN" to lazy { Currency("NGN", 566, 2, "Naira", listOf("Nigeria"), "₦") },
    "NIO" to lazy { Currency("NIO", 558, 2, "Cordoba Oro", listOf("Nicaragua"), "C$") },
    "NOK" to lazy { Currency("NOK", 578, 2, "Norwegian Krone", listOf("Bouvet Island", "Norway", "Svalbard and Jan Mayen"), "kr") },
    "NPR" to lazy { Currency("NPR", 524, 2, "Nepalese Rupee", listOf("Nepal"), "₨") },
    "NZD" to lazy { Currency("NZD", 554, 2, "New Zealand Dollar", listOf("Cook Islands (The)", "New Zealand", "Niue", "Pitcairn", "Tokelau"), "$") },
    "OMR" to lazy { Currency("OMR", 512, 3, "Omani Rial", listOf("Oman"), "﷼") },
    "PAB" to lazy { Currency("PAB", 590, 2, "Balboa", listOf("Panama"), "B/.") },
    "PEN" to lazy { Currency("PEN", 604, 2, "Sol", listOf("Peru"), "S/.") },
    "PGK" to lazy { Currency("PGK", 598, 2, "Kina", listOf("Papua New Guinea"), "K") },
    "PHP" to lazy { Currency("PHP", 608, 2, "Philippine Peso", listOf("Philippines (The)"), "₱") },
    "PKR" to lazy { Currency("PKR", 586, 2, "Pakistan Rupee", listOf("Pakistan"), "₨") },
    "PLN" to lazy { Currency("PLN", 985, 2, "Zloty", listOf("Poland"), "zł") },
    "PYG" to lazy { Currency("PYG", 600, 0, "Guarani", listOf("Paraguay"), "Gs") },
    "QAR" to lazy { Currency("QAR", 634, 2, "Qatari Riyal", listOf("Qatar"), "﷼") },
) .mapValues { it.value.value }
