package io.github.aughtone.types.financial

import io.github.aughtone.types.util.lazyMapOf

expect fun currencyFor(currencyCode: String): Currency?

internal data class CurrencyInfo(val displayName: String, val numericCode: Int)

/**
 * Data Source: https://www.iso.org/iso-4217-currency-codes.html
 *
 * This map is meant to supplement information on platforms that don't normally contain it.
 *
 * A map containing currency data, keyed by the three-letter ISO 4217 currency code.
 * Each entry's value is a lambda that returns a [CurrencyInfo] object, which
 * contains the currency's display name and numeric code.
 *
 * This map is lazily initialized using [lazyMapOf], meaning the values are
 * computed only when they are first accessed.
 *
 * The data includes both standard currencies and special codes like precious
 * metals, testing codes and No currency involved.
 *
 * @see CurrencyInfo
 * @see lazyMapOf
 */
internal val currencyDataMap = lazyMapOf(
    "AFN" to { CurrencyInfo("Afghani", 971) },
    "EUR" to { CurrencyInfo("Euro", 978) },
    "ALL" to { CurrencyInfo("Lek", 8) },
    "DZD" to { CurrencyInfo("Algerian Dinar", 12) },
    "USD" to { CurrencyInfo("US Dollar", 840) },
    "AOA" to { CurrencyInfo("Kwanza", 973) },
    "XCD" to { CurrencyInfo("East Caribbean Dollar", 951) },
    "ARS" to { CurrencyInfo("Argentine Peso", 32) },
    "AMD" to { CurrencyInfo("Armenian Dram", 51) },
    "AWG" to { CurrencyInfo("Aruban Florin", 533) },
    "AUD" to { CurrencyInfo("Australian Dollar", 36) },
    "AZN" to { CurrencyInfo("Azerbaijan Manat", 944) },
    "BSD" to { CurrencyInfo("Bahamian Dollar", 44) },
    "BHD" to { CurrencyInfo("Bahraini Dinar", 48) },
    "BDT" to { CurrencyInfo("Taka", 50) },
    "BBD" to { CurrencyInfo("Barbados Dollar", 52) },
    "BYN" to { CurrencyInfo("Belarusian Ruble", 933) },
    "BZD" to { CurrencyInfo("Belize Dollar", 84) },
    "XOF" to { CurrencyInfo("CFA Franc BCEAO", 952) },
    "BMD" to { CurrencyInfo("Bermudian Dollar", 60) },
    "INR" to { CurrencyInfo("Indian Rupee", 356) },
    "BTN" to { CurrencyInfo("Ngultrum", 64) },
    "BOB" to { CurrencyInfo("Boliviano", 68) },
    "BOV" to { CurrencyInfo("Mvdol", 984) },
    "BAM" to { CurrencyInfo("Convertible Mark", 977) },
    "BWP" to { CurrencyInfo("Pula", 72) },
    "NOK" to { CurrencyInfo("Norwegian Krone", 578) },
    "BRL" to { CurrencyInfo("Brazilian Real", 986) },
    "BND" to { CurrencyInfo("Brunei Dollar", 96) },
    "BGN" to { CurrencyInfo("Bulgarian Lev", 975) },
    "BIF" to { CurrencyInfo("Burundi Franc", 108) },
    "CVE" to { CurrencyInfo("Cabo Verde Escudo", 132) },
    "KHR" to { CurrencyInfo("Riel", 116) },
    "XAF" to { CurrencyInfo("CFA Franc BEAC", 950) },
    "CAD" to { CurrencyInfo("Canadian Dollar", 124) },
    "KYD" to { CurrencyInfo("Cayman Islands Dollar", 136) },
    "CLP" to { CurrencyInfo("Chilean Peso", 152) },
    "CLF" to { CurrencyInfo("Unidad de Fomento", 990) },
    "CNY" to { CurrencyInfo("Yuan Renminbi", 156) },
    "COP" to { CurrencyInfo("Colombian Peso", 170) },
    "COU" to { CurrencyInfo("Unidad de Valor Real", 970) },
    "KMF" to { CurrencyInfo("Comorian Franc ", 174) },
    "CDF" to { CurrencyInfo("Congolese Franc", 976) },
    "NZD" to { CurrencyInfo("New Zealand Dollar", 554) },
    "CRC" to { CurrencyInfo("Costa Rican Colon", 188) },
    "CUP" to { CurrencyInfo("Cuban Peso", 192) },
    "ANG" to { CurrencyInfo("Netherlands Antillean Guilder", 532) },
    "CZK" to { CurrencyInfo("Czech Koruna", 203) },
    "DKK" to { CurrencyInfo("Danish Krone", 208) },
    "DJF" to { CurrencyInfo("Djibouti Franc", 262) },
    "DOP" to { CurrencyInfo("Dominican Peso", 214) },
    "EGP" to { CurrencyInfo("Egyptian Pound", 818) },
    "SVC" to { CurrencyInfo("El Salvador Colon", 222) },
    "ERN" to { CurrencyInfo("Nakfa", 232) },
    "SZL" to { CurrencyInfo("Lilangeni", 748) },
    "ETB" to { CurrencyInfo("Ethiopian Birr", 230) },
    "FKP" to { CurrencyInfo("Falkland Islands Pound", 238) },
    "FJD" to { CurrencyInfo("Fiji Dollar", 242) },
    "XPF" to { CurrencyInfo("CFP Franc", 953) },
    "GMD" to { CurrencyInfo("Dalasi", 270) },
    "GEL" to { CurrencyInfo("Lari", 981) },
    "GHS" to { CurrencyInfo("Ghana Cedi", 936) },
    "GIP" to { CurrencyInfo("Gibraltar Pound", 292) },
    "GTQ" to { CurrencyInfo("Quetzal", 320) },
    "GBP" to { CurrencyInfo("Pound Sterling", 826) },
    "GNF" to { CurrencyInfo("Guinean Franc", 324) },
    "GYD" to { CurrencyInfo("Guyana Dollar", 328) },
    "HTG" to { CurrencyInfo("Gourde", 332) },
    "HNL" to { CurrencyInfo("Lempira", 340) },
    "HKD" to { CurrencyInfo("Hong Kong Dollar", 344) },
    "HUF" to { CurrencyInfo("Forint", 348) },
    "ISK" to { CurrencyInfo("Iceland Krona", 352) },
    "IDR" to { CurrencyInfo("Rupiah", 360) },
    "XDR" to { CurrencyInfo("SDR (Special Drawing Right)", 960) },
    "IRR" to { CurrencyInfo("Iranian Rial", 364) },
    "IQD" to { CurrencyInfo("Iraqi Dinar", 368) },
    "ILS" to { CurrencyInfo("New Israeli Sheqel", 376) },
    "JMD" to { CurrencyInfo("Jamaican Dollar", 388) },
    "JPY" to { CurrencyInfo("Yen", 392) },
    "JOD" to { CurrencyInfo("Jordanian Dinar", 400) },
    "KZT" to { CurrencyInfo("Tenge", 398) },
    "KES" to { CurrencyInfo("Kenyan Shilling", 404) },
    "KPW" to { CurrencyInfo("North Korean Won", 408) },
    "KRW" to { CurrencyInfo("Won", 410) },
    "KWD" to { CurrencyInfo("Kuwaiti Dinar", 414) },
    "KGS" to { CurrencyInfo("Som", 417) },
    "LAK" to { CurrencyInfo("Lao Kip", 418) },
    "LBP" to { CurrencyInfo("Lebanese Pound", 422) },
    "LSL" to { CurrencyInfo("Loti", 426) },
    "ZAR" to { CurrencyInfo("Rand", 710) },
    "LRD" to { CurrencyInfo("Liberian Dollar", 430) },
    "LYD" to { CurrencyInfo("Libyan Dinar", 434) },
    "CHF" to { CurrencyInfo("Swiss Franc", 756) },
    "MOP" to { CurrencyInfo("Pataca", 446) },
    "MKD" to { CurrencyInfo("Denar", 807) },
    "MGA" to { CurrencyInfo("Malagasy Ariary", 969) },
    "MWK" to { CurrencyInfo("Malawi Kwacha", 454) },
    "MYR" to { CurrencyInfo("Malaysian Ringgit", 458) },
    "MVR" to { CurrencyInfo("Rufiyaa", 462) },
    "MRU" to { CurrencyInfo("Ouguiya", 929) },
    "MUR" to { CurrencyInfo("Mauritius Rupee", 480) },
    "XUA" to { CurrencyInfo("ADB Unit of Account", 965) },
    "MXN" to { CurrencyInfo("Mexican Peso", 484) },
    "MXV" to { CurrencyInfo("Mexican Unidad de Inversion (UDI)", 979) },
    "MDL" to { CurrencyInfo("Moldovan Leu", 498) },
    "MNT" to { CurrencyInfo("Tugrik", 496) },
    "MAD" to { CurrencyInfo("Moroccan Dirham", 504) },
    "MZN" to { CurrencyInfo("Mozambique Metical", 943) },
    "MMK" to { CurrencyInfo("Kyat", 104) },
    "NAD" to { CurrencyInfo("Namibia Dollar", 516) },
    "NPR" to { CurrencyInfo("Nepalese Rupee", 524) },
    "NIO" to { CurrencyInfo("Cordoba Oro", 558) },
    "NGN" to { CurrencyInfo("Naira", 566) },
    "OMR" to { CurrencyInfo("Rial Omani", 512) },
    "PKR" to { CurrencyInfo("Pakistan Rupee", 586) },
    "PAB" to { CurrencyInfo("Balboa", 590) },
    "PGK" to { CurrencyInfo("Kina", 598) },
    "PYG" to { CurrencyInfo("Guarani", 600) },
    "PEN" to { CurrencyInfo("Sol", 604) },
    "PHP" to { CurrencyInfo("Philippine Peso", 608) },
    "PLN" to { CurrencyInfo("Zloty", 985) },
    "QAR" to { CurrencyInfo("Qatari Rial", 634) },
    "RON" to { CurrencyInfo("Romanian Leu", 946) },
    "RUB" to { CurrencyInfo("Russian Ruble", 643) },
    "RWF" to { CurrencyInfo("Rwanda Franc", 646) },
    "SHP" to { CurrencyInfo("Saint Helena Pound", 654) },
    "WST" to { CurrencyInfo("Tala", 882) },
    "STN" to { CurrencyInfo("Dobra", 930) },
    "SAR" to { CurrencyInfo("Saudi Riyal", 682) },
    "RSD" to { CurrencyInfo("Serbian Dinar", 941) },
    "SCR" to { CurrencyInfo("Seychelles Rupee", 690) },
    "SLE" to { CurrencyInfo("Leone", 925) },
    "SGD" to { CurrencyInfo("Singapore Dollar", 702) },
    "XSU" to { CurrencyInfo("Sucre", 994) },
    "SBD" to { CurrencyInfo("Solomon Islands Dollar", 90) },
    "SOS" to { CurrencyInfo("Somali Shilling", 706) },
    "SSP" to { CurrencyInfo("South Sudanese Pound", 728) },
    "LKR" to { CurrencyInfo("Sri Lanka Rupee", 144) },
    "SDG" to { CurrencyInfo("Sudanese Pound", 938) },
    "SRD" to { CurrencyInfo("Surinam Dollar", 968) },
    "SEK" to { CurrencyInfo("Swedish Krona", 752) },
    "CHE" to { CurrencyInfo("WIR Euro", 947) },
    "CHW" to { CurrencyInfo("WIR Franc", 948) },
    "SYP" to { CurrencyInfo("Syrian Pound", 760) },
    "TWD" to { CurrencyInfo("New Taiwan Dollar", 901) },
    "TJS" to { CurrencyInfo("Somoni", 972) },
    "TZS" to { CurrencyInfo("Tanzanian Shilling", 834) },
    "THB" to { CurrencyInfo("Baht", 764) },
    "TOP" to { CurrencyInfo("Pa’anga", 776) },
    "TTD" to { CurrencyInfo("Trinidad and Tobago Dollar", 780) },
    "TND" to { CurrencyInfo("Tunisian Dinar", 788) },
    "TRY" to { CurrencyInfo("Turkish Lira", 949) },
    "TMT" to { CurrencyInfo("Turkmenistan New Manat", 934) },
    "UGX" to { CurrencyInfo("Uganda Shilling", 800) },
    "UAH" to { CurrencyInfo("Hryvnia", 980) },
    "AED" to { CurrencyInfo("UAE Dirham", 784) },
    "USN" to { CurrencyInfo("US Dollar (Next day)", 997) },
    "UYU" to { CurrencyInfo("Peso Uruguayo", 858) },
    "UYI" to { CurrencyInfo("Uruguay Peso en Unidades Indexadas (UI)", 940) },
    "UYW" to { CurrencyInfo("Unidad Previsional", 927) },
    "UZS" to { CurrencyInfo("Uzbekistan Sum", 860) },
    "VUV" to { CurrencyInfo("Vatu", 548) },
    "VES" to { CurrencyInfo("Bolívar Soberano", 928) },
    "VED" to { CurrencyInfo("Bolívar Soberano", 926) },
    "VND" to { CurrencyInfo("Dong", 704) },
    "YER" to { CurrencyInfo("Yemeni Rial", 886) },
    "ZMW" to { CurrencyInfo("Zambian Kwacha", 967) },
    "ZWG" to { CurrencyInfo("Zimbabwe Gold", 924) },
    "XBA" to { CurrencyInfo("Bond Markets Unit European Composite Unit (EURCO)", 955) },
    "XBB" to { CurrencyInfo("Bond Markets Unit European Monetary Unit (E.M.U.-6)", 956) },
    "XBC" to { CurrencyInfo("Bond Markets Unit European Unit of Account 9 (E.U.A.-9)", 957) },
    "XBD" to { CurrencyInfo("Bond Markets Unit European Unit of Account 17 (E.U.A.-17)", 958) },
    "XTS" to { CurrencyInfo("Codes specifically reserved for testing purposes", 963) },
    "XXX" to {
        CurrencyInfo(
            "The codes assigned for transactions where no currency is involved",
            999
        )
    },
    "XAU" to { CurrencyInfo("Gold", 959) },
    "XPD" to { CurrencyInfo("Palladium", 964) },
    "XPT" to { CurrencyInfo("Platinum", 962) },
    "XAG" to { CurrencyInfo("Silver", 961) },
)

internal val currencySymbols: Map<String, String> = mapOf(
    "AED" to "د.إ",
    "AFN" to "؋",
    "ALL" to "L",
    "AMD" to "֏",
    "ANG" to "ƒ",
    "AOA" to "Kz",
    "ARS" to "$",
    "AUD" to "$",
    "AWG" to "ƒ",
    "AZN" to "₼",
    "BAM" to "KM",
    "BBD" to "$",
    "BDT" to "৳",
    "BGN" to "лв",
    "BHD" to ".د.ب",
    "BIF" to "FBu",
    "BMD" to "$",
    "BND" to "$",
    "BOB" to "\$b",
    "BOV" to "BOV",
    "BRL" to "R$",
    "BSD" to "$",
    "BTC" to "₿",
    "BTN" to "Nu.",
    "BWP" to "P",
    "BYN" to "Br",
    "BYR" to "Br",
    "BZD" to "BZ$",
    "CAD" to "$",
    "CDF" to "FC",
    "CHE" to "CHE",
    "CHF" to "CHF",
    "CHW" to "CHW",
    "CLF" to "CLF",
    "CLP" to "$",
    "CNH" to "¥",
    "CNY" to "¥",
    "COP" to "$",
    "COU" to "COU",
    "CRC" to "₡",
    "CUC" to "$",
    "CUP" to "₱",
    "CVE" to "$",
    "CZK" to "Kč",
    "DJF" to "Fdj",
    "DKK" to "kr",
    "DOP" to "RD$",
    "DZD" to "دج",
    "EEK" to "kr",
    "EGP" to "£",
    "ERN" to "Nfk",
    "ETB" to "Br",
    "ETH" to "Ξ",
    "EUR" to "€",
    "FJD" to "$",
    "FKP" to "£",
    "GBP" to "£",
    "GEL" to "₾",
    "GGP" to "£",
    "GHC" to "₵",
    "GHS" to "GH₵",
    "GIP" to "£",
    "GMD" to "D",
    "GNF" to "FG",
    "GTQ" to "Q",
    "GYD" to "$",
    "HKD" to "$",
    "HNL" to "L",
    "HRK" to "kn",
    "HTG" to "G",
    "HUF" to "Ft",
    "IDR" to "Rp",
    "ILS" to "₪",
    "IMP" to "£",
    "INR" to "₹",
    "IQD" to "ع.د",
    "IRR" to "﷼",
    "ISK" to "kr",
    "JEP" to "£",
    "JMD" to "J$",
    "JOD" to "JD",
    "JPY" to "¥",
    "KES" to "KSh",
    "KGS" to "лв",
    "KHR" to "៛",
    "KMF" to "CF",
    "KPW" to "₩",
    "KRW" to "₩",
    "KWD" to "KD",
    "KYD" to "$",
    "KZT" to "₸",
    "LAK" to "₭",
    "LBP" to "£",
    "LKR" to "₨",
    "LRD" to "$",
    "LSL" to "M",
    "LTC" to "Ł",
    "LTL" to "Lt",
    "LVL" to "Ls",
    "LYD" to "LD",
    "MAD" to "MAD",
    "MDL" to "lei",
    "MGA" to "Ar",
    "MKD" to "ден",
    "MMK" to "K",
    "MNT" to "₮",
    "MOP" to "MOP$",
    "MRO" to "UM",
    "MRU" to "UM",
    "MUR" to "₨",
    "MVR" to "Rf",
    "MWK" to "MK",
    "MXN" to "$",
    "MXV" to "MXV",
    "MYR" to "RM",
    "MZN" to "MT",
    "NAD" to "$",
    "NGN" to "₦",
    "NIO" to "C$",
    "NOK" to "kr",
    "NPR" to "₨",
    "NZD" to "$",
    "OMR" to "﷼",
    "PAB" to "B/.",
    "PEN" to "S/.",
    "PGK" to "K",
    "PHP" to "₱",
    "PKR" to "₨",
    "PLN" to "zł",
    "PYG" to "Gs",
    "QAR" to "﷼",
    "RMB" to "￥",
    "RON" to "lei",
    "RSD" to "Дин.",
    "RUB" to "₽",
    "RWF" to "R₣",
    "SAR" to "﷼",
    "SBD" to "$",
    "SCR" to "₨",
    "SDG" to "ج.س.",
    "SEK" to "kr",
    "SGD" to "S$",
    "SHP" to "£",
    "SLL" to "Le",
    "SOS" to "S",
    "SRD" to "$",
    "SSP" to "£",
    "STD" to "Db",
    "STN" to "Db",
    "SVC" to "$",
    "SYP" to "£",
    "SZL" to "E",
    "THB" to "฿",
    "TJS" to "SM",
    "TMT" to "T",
    "TND" to "د.ت",
    "TOP" to "T$",
    "TRL" to "₤",
    "TRY" to "₺",
    "TTD" to "TT$",
    "TVD" to "$",
    "TWD" to "NT$",
    "TZS" to "TSh",
    "UAH" to "₴",
    "UGX" to "USh",
    "USD" to "$",
    "UYI" to "UYI",
    "UYU" to "\$U",
    "UYW" to "UYW",
    "UZS" to "лв",
    "VEF" to "Bs",
    "VES" to "Bs.S",
    "VND" to "₫",
    "VUV" to "VT",
    "WST" to "WS$",
    "XAF" to "FCFA",
    "XBT" to "Ƀ",
    "XCD" to "$",
    "XOF" to "CFA",
    "XPF" to "₣",
    "XSU" to "Sucre",
    "XUA" to "XUA",
    "YER" to "﷼",
    "ZAR" to "R",
    "ZMW" to "ZK",
    "ZWD" to "Z$",
    "ZWL" to "$"
)
