package io.github.aughtone.types.financial

internal data class CurrencyResource(
    val code: String,
    val number: Int,
    val digits: Int,
    val currency: String,
    val countries: List<String>,
    val symbol: String // Added the symbol property
)

internal val jsCurrencyData = listOf(
    CurrencyResource("AED", 784, 2, "UAE Dirham", listOf("United Arab Emirates (The)"), "د.إ"),
    CurrencyResource("AFN", 971, 2, "Afghani", listOf("Afghanistan"), "؋"),
    CurrencyResource("ALL", 8, 2, "Lek", listOf("Albania"), "L"),
    CurrencyResource("AMD", 51, 2, "Armenian Dram", listOf("Armenia"), "֏"),
    CurrencyResource("ANG", 532, 2, "Netherlands Antillean Guilder", listOf("Curaçao", "Sint Maarten (Dutch Part)"), "ƒ"),
    CurrencyResource("AOA", 973, 2, "Kwanza", listOf("Angola"), "Kz"),
    CurrencyResource("ARS", 32, 2, "Argentine Peso", listOf("Argentina"), "$"),
    CurrencyResource("AUD", 36, 2, "Australian Dollar", listOf("Australia", "Christmas Island", "Cocos (Keeling) Islands (The)", "Heard Island and Mcdonald Islands", "Kiribati", "Nauru", "Norfolk Island", "Tuvalu"), "$"),
    CurrencyResource("AWG", 533, 2, "Aruban Florin", listOf("Aruba"), "ƒ"),
    CurrencyResource("AZN", 944, 2, "Azerbaijan Manat", listOf("Azerbaijan"), "₼"),
    CurrencyResource("BAM", 977, 2, "Convertible Mark", listOf("Bosnia and Herzegovina"), "KM"),
    CurrencyResource("BBD", 52, 2, "Barbados Dollar", listOf("Barbados"), "$"),
    CurrencyResource("BDT", 50, 2, "Taka", listOf("Bangladesh"), "৳"),
    CurrencyResource("BGN", 975, 2, "Bulgarian Lev", listOf("Bulgaria"), "лв"),
    CurrencyResource("BHD", 48, 3, "Bahraini Dinar", listOf("Bahrain"), ".د.ب"),
    CurrencyResource("BIF", 108, 0, "Burundi Franc", listOf("Burundi"), "FBu"),
    CurrencyResource("BMD", 60, 2, "Bermudian Dollar", listOf("Bermuda"), "$"),
    CurrencyResource("BND", 96, 2, "Brunei Dollar", listOf("Brunei Darussalam"), "$"),
    CurrencyResource("BOB", 68, 2, "Boliviano", listOf("Bolivia (Plurinational State Of)"), "\$b"),
    CurrencyResource("BOV", 984, 2, "Mvdol", listOf("Bolivia (Plurinational State Of)"), "BOV"),
    CurrencyResource("BRL", 986, 2, "Brazilian Real", listOf("Brazil"), "R$"),
    CurrencyResource("BSD", 44, 2, "Bahamian Dollar", listOf("Bahamas (The)"), "$"),
    CurrencyResource("BTN", 64, 2, "Ngultrum", listOf("Bhutan"), "Nu."),
    CurrencyResource("BWP", 72, 2, "Pula", listOf("Botswana"), "P"),
    CurrencyResource("BYN", 933, 2, "Belarusian Ruble", listOf("Belarus"), "Br"),
    CurrencyResource("BZD", 84, 2, "Belize Dollar", listOf("Belize"), "BZ$"),
    CurrencyResource("CAD", 124, 2, "Canadian Dollar", listOf("Canada"), "$"),
    CurrencyResource("CDF", 976, 2, "Congolese Franc", listOf("Congo (The Democratic Republic of The)"), "FC"),
    CurrencyResource("CHE", 947, 2, "WIR Euro", listOf("Switzerland"), "CHE"),
    CurrencyResource("CHF", 756, 2, "Swiss Franc", listOf("Liechtenstein", "Switzerland"), "CHF"),
    CurrencyResource("CHW", 948, 2, "WIR Franc", listOf("Switzerland"), "CHW"),
    CurrencyResource("CLF", 990, 4, "Unidad de Fomento", listOf("Chile"), "CLF"),
    CurrencyResource("CLP", 152, 0, "Chilean Peso", listOf("Chile"), "$"),
    CurrencyResource("CNY", 156, 2, "Yuan Renminbi", listOf("China"), "¥"),
    CurrencyResource("COP", 170, 2, "Colombian Peso", listOf("Colombia"), "$"),
    CurrencyResource("COU", 970, 2, "Unidad de Valor Real", listOf("Colombia"), "COU"),
    CurrencyResource("CRC", 188, 2, "Costa Rican Colon", listOf("Costa Rica"), "₡"),
    CurrencyResource("CUC", 931, 2, "Peso Convertible", listOf("Cuba"), "$"),
    CurrencyResource("CUP", 192, 2, "Cuban Peso", listOf("Cuba"), "₱"),
    CurrencyResource("CVE", 132, 2, "Cabo Verde Escudo", listOf("Cabo Verde"), "$"),
    CurrencyResource("CZK", 203, 2, "Czech Koruna", listOf("Czechia"), "Kč"),
    CurrencyResource("DJF", 262, 0, "Djibouti Franc", listOf("Djibouti"), "Fdj"),
    CurrencyResource("DKK", 208, 2, "Danish Krone", listOf("Denmark", "Faroe Islands (The)", "Greenland"), "kr"),
    CurrencyResource("DOP", 214, 2, "Dominican Peso", listOf("Dominican Republic (The)"), "RD$"),
    CurrencyResource("DZD", 12, 2, "Algerian Dinar", listOf("Algeria"), "دج"),
    CurrencyResource("EGP", 818, 2, "Egyptian Pound", listOf("Egypt"), "£"),
    CurrencyResource("ERN", 232, 2, "Nakfa", listOf("Eritrea"), "Nfk"),
    CurrencyResource("ETB", 230, 2, "Ethiopian Birr", listOf("Ethiopia"), "Br"),
    CurrencyResource("EUR", 978, 2, "Euro", listOf("Åland Islands", "Andorra", "Austria", "Belgium", "Croatia", "Cyprus", "Estonia", "European Union", "Finland", "France", "French Guiana", "French Southern Territories (The)", "Germany", "Greece", "Guadeloupe", "Holy See (The)", "Ireland", "Italy", "Latvia", "Lithuania", "Luxembourg", "Malta", "Martinique", "Mayotte", "Monaco", "Montenegro", "Netherlands (The)", "Portugal", "Réunion", "Saint Barthélemy", "Saint Martin (French Part)", "Saint Pierre and Miquelon", "San Marino", "Slovakia", "Slovenia", "Spain"), "€"),
    CurrencyResource("FJD", 242, 2, "Fiji Dollar", listOf("Fiji"), "$"),
    CurrencyResource("FKP", 238, 2, "Falkland Islands Pound", listOf("Falkland Islands (The) [Malvinas]"), "£"),
    CurrencyResource("GBP", 826, 2, "Pound Sterling", listOf("Guernsey", "Isle of Man", "Jersey", "United Kingdom of Great Britain and Northern Ireland (The)"), "£"),
    CurrencyResource("GEL", 981, 2, "Lari", listOf("Georgia"), "₾"),
    CurrencyResource("GHS", 936, 2, "Ghana Cedi", listOf("Ghana"), "GH₵"),
    CurrencyResource("GIP", 292, 2, "Gibraltar Pound", listOf("Gibraltar"), "£"),
    CurrencyResource("GMD", 270, 2, "Dalasi", listOf("Gambia (The)"), "D"),
    CurrencyResource("GNF", 324, 0, "Guinean Franc", listOf("Guinea"), "FG"),
    CurrencyResource("GTQ", 320, 2, "Quetzal", listOf("Guatemala"), "Q"),
    CurrencyResource("GYD", 328, 2, "Guyana Dollar", listOf("Guyana"), "$"),
    CurrencyResource("HKD", 344, 2, "Hong Kong Dollar", listOf("Hong Kong"), "$"),
    CurrencyResource("HNL", 340, 2, "Lempira", listOf("Honduras"), "L"),
    CurrencyResource("HTG", 332, 2, "Gourde", listOf("Haiti"), "G"),
    CurrencyResource("HUF", 348, 2, "Forint", listOf("Hungary"), "Ft"),
    CurrencyResource("IDR", 360, 2, "Rupiah", listOf("Indonesia"), "Rp"),
    CurrencyResource("ILS", 376, 2, "New Israeli Sheqel", listOf("Israel"), "₪"),
    CurrencyResource("INR", 356, 2, "Indian Rupee", listOf("Bhutan", "India"), "₹"),
    CurrencyResource("IQD", 368, 3, "Iraqi Dinar", listOf("Iraq"), "ع.د"),
    CurrencyResource("IRR", 364, 2, "Iranian Rial", listOf("Iran (Islamic Republic Of)"), "﷼"),
    CurrencyResource("ISK", 352, 0, "Iceland Krona", listOf("Iceland"), "kr"),
    CurrencyResource("JMD", 388, 2, "Jamaican Dollar", listOf("Jamaica"), "J$"),
    CurrencyResource("JOD", 400, 3, "Jordanian Dinar", listOf("Jordan"), "JD"),
    CurrencyResource("JPY", 392, 0, "Yen", listOf("Japan"), "¥"),
    CurrencyResource("KES", 404, 2, "Kenyan Shilling", listOf("Kenya"), "KSh"),
    CurrencyResource("KGS", 417, 2, "Som", listOf("Kyrgyzstan"), "лв"),
    CurrencyResource("KHR", 116, 2, "Riel", listOf("Cambodia"), "៛"),
    CurrencyResource("KMF", 174, 0, "Comorian Franc ", listOf("Comoros (The)"), "CF"),
    CurrencyResource("KPW", 408, 2, "North Korean Won", listOf("Korea (The Democratic People’s Republic Of)"), "₩"),
    CurrencyResource("KRW", 410, 0, "Won", listOf("Korea (The Republic Of)"), "₩"),
    CurrencyResource("KWD", 414, 3, "Kuwaiti Dinar", listOf("Kuwait"), "KD"),
    CurrencyResource("KYD", 136, 2, "Cayman Islands Dollar", listOf("Cayman Islands (The)"), "$"),
    CurrencyResource("KZT", 398, 2, "Tenge", listOf("Kazakhstan"), "₸"),
    CurrencyResource("LAK", 418, 2, "Lao Kip", listOf("Lao People’s Democratic Republic (The)"), "₭"),
    CurrencyResource("LBP", 422, 2, "Lebanese Pound", listOf("Lebanon"), "£"),
    CurrencyResource("LKR", 144, 2, "Sri Lanka Rupee", listOf("Sri Lanka"), "₨"),
    CurrencyResource("LRD", 430, 2, "Liberian Dollar", listOf("Liberia"), "$"),
    CurrencyResource("LSL", 426, 2, "Loti", listOf("Lesotho"), "M"),
    CurrencyResource("LYD", 434, 3, "Libyan Dinar", listOf("Libya"), "LD"),
    CurrencyResource("MAD", 504, 2, "Moroccan Dirham", listOf("Morocco", "Western Sahara"), "MAD"),
    CurrencyResource("MDL", 498, 2, "Moldovan Leu", listOf("Moldova (The Republic Of)"), "lei"),
    CurrencyResource("MGA", 969, 2, "Malagasy Ariary", listOf("Madagascar"), "Ar"),
    CurrencyResource("MKD", 807, 2, "Denar", listOf("North Macedonia"), "ден"),
    CurrencyResource("MMK", 104, 2, "Kyat", listOf("Myanmar"), "K"),
    CurrencyResource("MNT", 496, 2, "Tugrik", listOf("Mongolia"), "₮"),
    CurrencyResource("MOP", 446, 2, "Pataca", listOf("Macao"), "MOP$"),
    CurrencyResource("MRU", 929, 2, "Ouguiya", listOf("Mauritania"), "UM"),
    CurrencyResource("MUR", 480, 2, "Mauritius Rupee", listOf("Mauritius"), "₨"),
    CurrencyResource("MVR", 462, 2, "Rufiyaa", listOf("Maldives"), "Rf"),
    CurrencyResource("MWK", 454, 2, "Malawi Kwacha", listOf("Malawi"), "MK"),
    CurrencyResource("MXN", 484, 2, "Mexican Peso", listOf("Mexico"), "$"),
    CurrencyResource("MXV", 979, 2, "Mexican Unidad de Inversion (UDI)", listOf("Mexico"), "MXV"),
    CurrencyResource("MYR", 458, 2, "Malaysian Ringgit", listOf("Malaysia"), "RM"),
    CurrencyResource("MZN", 943, 2, "Mozambique Metical", listOf("Mozambique"), "MT"),
    CurrencyResource("NAD", 516, 2, "Namibia Dollar", listOf("Namibia"), "$"),
    CurrencyResource("NGN", 566, 2, "Naira", listOf("Nigeria"), "₦"),
    CurrencyResource("NIO", 558, 2, "Cordoba Oro", listOf("Nicaragua"), "C$"),
    CurrencyResource("NOK", 578, 2, "Norwegian Krone", listOf("Bouvet Island", "Norway", "Svalbard and Jan Mayen"), "kr"),
    CurrencyResource("NPR", 524, 2, "Nepalese Rupee", listOf("Nepal"), "₨"),
    CurrencyResource("NZD", 554, 2, "New Zealand Dollar", listOf("Cook Islands (The)", "New Zealand", "Niue", "Pitcairn", "Tokelau"), "$"),
    CurrencyResource("OMR", 512, 3, "Rial Omani", listOf("Oman"), "﷼"),
    CurrencyResource("PAB", 590, 2, "Balboa", listOf("Panama"), "B/."),
    CurrencyResource("PEN", 604, 2, "Sol", listOf("Peru"), "S/."),
    CurrencyResource("PGK", 598, 2, "Kina", listOf("Papua New Guinea"), "K"),
    CurrencyResource("PHP", 608, 2, "Philippine Peso", listOf("Philippines (The)"), "₱"),
    CurrencyResource("PKR", 586, 2, "Pakistan Rupee", listOf("Pakistan"), "₨"),
    CurrencyResource("PLN", 985, 2, "Zloty", listOf("Poland"), "zł"),
    CurrencyResource("PYG", 600, 0, "Guarani", listOf("Paraguay"), "Gs"),
    CurrencyResource("QAR", 634, 2, "Qatari Rial", listOf("Qatar"), "﷼"),
)

internal val currencyResourceMap: Map<String, CurrencyResource> = jsCurrencyData.associateBy { it.code }
