package io.github.aughtone.types.financial

import io.github.aughtone.types.util.lazyMapOf

/**
 * Data Source: https://www.iso.org/iso-4217-currency-codes.html
 *
 * This map is meant to supplement curency information on platforms that don't normally contain it.
 *
 * A map containing currency data, keyed by the three-letter ISO 4217 currency code.
 * Each entry's value is a lambda that returns a [Currency] object, which
 * contains the currency's display name and numeric code.
 *
 * This map is lazily initialized using [lazyMapOf], meaning the values are
 * computed only when they are first accessed.
 *
 * The map does not contain any entries for special codes like precious metals, testing, or No currency involved.
 *
 * @see Currency
 * @see lazyMapOf
 */

internal val currencyResourceMap: Map<String, Currency> = lazyMapOf(
    "AED" to { Currency("AED", 784, 2, "UAE Dirham",  "د.إ") },
    "AFN" to { Currency("AFN", 971, 2, "Afghani",   "؋") },
    "ALL" to { Currency("ALL", 8, 2, "Lek",  "L") },
    "AMD" to { Currency("AMD", 51, 2, "Armenian Dram",   "֏") },
    "ANG" to { Currency("ANG", 532, 2, "Netherlands Antillean Guilder", "ƒ", obsolete = true, replacedBy = "XCG") },
    "AOA" to { Currency("AOA", 973, 2, "Kwanza",  "Kz") },
    "ARS" to { Currency("ARS", 32, 2, "Argentine Peso",  "$") },
    "AUD" to { Currency("AUD", 36, 2, "Australian Dollar",  "$") },
    "AWG" to { Currency("AWG", 533, 2, "Aruban Florin",  "ƒ") },
    "AZN" to { Currency("AZN", 944, 2, "Azerbaijan Manat",  "₼") },
    "BAM" to { Currency("BAM", 977, 2, "Convertible Mark",  "KM") },
    "BBD" to { Currency("BBD", 52, 2, "Barbados Dollar",  "$") },
    "BDT" to { Currency("BDT", 50, 2, "Taka",  "৳") },
    "BGN" to { Currency("BGN", 975, 2, "Bulgarian Lev",  "лв") },
    "BHD" to { Currency("BHD", 48, 3, "Bahraini Dinar",  ".د.ب") },
    "BIF" to { Currency("BIF", 108, 0, "Burundi Franc",  "FBu") },
    "BMD" to { Currency("BMD", 60, 2, "Bermudian Dollar",  "$") },
    "BND" to { Currency("BND", 96, 2, "Brunei Dollar",  "$") },
    "BOB" to { Currency("BOB", 68, 2, "Boliviano",  "\$b") },
    "BOV" to { Currency("BOV", 984, 2, "Mvdol",  "BOV") },
    "BRL" to { Currency("BRL", 986, 2, "Brazilian Real",  "R$") },
    "BSD" to { Currency("BSD", 44, 2, "Bahamian Dollar",  "$") },
    "BTN" to { Currency("BTN", 64, 2, "Ngultrum",  "Nu.") },
    "BWP" to { Currency("BWP", 72, 2, "Pula",  "P") },
    "BYN" to { Currency("BYN", 933, 2, "Belarusian Ruble",  "Br") },
    "BZD" to { Currency("BZD", 84, 2, "Belize Dollar",  "BZ$") },
    "CAD" to { Currency("CAD", 124, 2, "Canadian Dollar",  "$") },
    "CDF" to { Currency("CDF", 976, 2, "Congolese Franc",  "FC") },
    "CHE" to { Currency("CHE", 947, 2, "WIR Euro",  "CHE") },
    "CHF" to { Currency("CHF", 756, 2, "Swiss Franc",  "CHF") },
    "CHW" to { Currency("CHW", 948, 2, "WIR Franc",  "CHW") },
    "CLF" to { Currency("CLF", 990, 4, "Unidad de Fomento",  "CLF") },
    "CLP" to { Currency("CLP", 152, 0, "Chilean Peso",  "$") },
    "CNY" to { Currency("CNY", 156, 2, "Yuan Renminbi",  "¥") },
    "COP" to { Currency("COP", 170, 2, "Colombian Peso",  "$") },
    "COU" to { Currency("COU", 970, 2, "Unidad de Valor Real",  "COU") },
    "CRC" to { Currency("CRC", 188, 2, "Costa Rican Colon",  "₡") },
    "CUC" to { Currency("CUC", 931, 2, "Peso Convertible",  "$") },
    "CUP" to { Currency("CUP", 192, 2, "Cuban Peso",  "₱") },
    "CVE" to { Currency("CVE", 132, 2, "Cabo Verde Escudo",  "$") },
    "CZK" to { Currency("CZK", 203, 2, "Czech Koruna",  "Kč") },
    "DJF" to { Currency("DJF", 262, 0, "Djibouti Franc",  "Fdj") },
    "DKK" to { Currency("DKK", 208, 2, "Danish Krone", "kr") },
    "DOP" to { Currency("DOP", 214, 2, "Dominican Peso", "RD$") },
    "DZD" to { Currency("DZD", 12, 2, "Algerian Dinar",  "دج") },
    "EGP" to { Currency("EGP", 818, 2, "Egyptian Pound",  "£") },
    "ERN" to { Currency("ERN", 232, 2, "Nakfa",  "Nfk") },
    "ETB" to { Currency("ETB", 230, 2, "Ethiopian Birr",  "Br") },
    "EUR" to { Currency("EUR", 978, 2, "Euro", "€") },
    "FJD" to { Currency("FJD", 242, 2, "Fiji Dollar",  "$") },
    "FKP" to { Currency("FKP", 238, 2, "Falkland Islands Pound", "£") },
    "GBP" to { Currency("GBP", 826, 2, "Pound Sterling",  "£") },
    "GEL" to { Currency("GEL", 981, 2, "Lari",  "₾") },
    "GHS" to { Currency("GHS", 936, 2, "Ghana Cedi",  "GH₵") },
    "GIP" to { Currency("GIP", 292, 2, "Gibraltar Pound",  "£") },
    "GMD" to { Currency("GMD", 270, 2, "Dalasi",  "D") },
    "GNF" to { Currency("GNF", 324, 0, "Guinean Franc",  "FG") },
    "GTQ" to { Currency("GTQ", 320, 2, "Quetzal",  "Q") },
    "GYD" to { Currency("GYD", 328, 2, "Guyana Dollar",  "$") },
    "HKD" to { Currency("HKD", 344, 2, "Hong Kong Dollar",  "$") },
    "HNL" to { Currency("HNL", 340, 2, "Lempira",  "L") },
    "HTG" to { Currency("HTG", 332, 2, "Gourde",  "G") },
    "HUF" to { Currency("HUF", 348, 2, "Forint",  "Ft") },
    "IDR" to { Currency("IDR", 360, 2, "Rupiah",  "Rp") },
    "ILS" to { Currency("ILS", 376, 2, "New Israeli Sheqel",  "₪") },
    "INR" to { Currency("INR", 356, 2, "Indian Rupee",  "₹") },
    "IQD" to { Currency("IQD", 368, 3, "Iraqi Dinar",  "ع.د") },
    "IRR" to { Currency("IRR", 364, 2, "Iranian Rial",  "﷼") },
    "ISK" to { Currency("ISK", 352, 0, "Iceland Krona",  "kr") },
    "JMD" to { Currency("JMD", 388, 2, "Jamaican Dollar",  "J$") },
    "JOD" to { Currency("JOD", 400, 3, "Jordanian Dinar",  "JD") },
    "JPY" to { Currency("JPY", 392, 0, "Yen",  "¥") },
    "KES" to { Currency("KES", 404, 2, "Kenyan Shilling",  "KSh") },
    "KGS" to { Currency("KGS", 417, 2, "Som",  "лв") },
    "KHR" to { Currency("KHR", 116, 2, "Riel",  "៛") },
    "KMF" to { Currency("KMF", 174, 0, "Comorian Franc ",  "CF") },
    "KPW" to { Currency("KPW", 408, 2, "North Korean Won",  "₩") },
    "KRW" to { Currency("KRW", 410, 0, "Won",  "₩") },
    "KWD" to { Currency("KWD", 414, 3, "Kuwaiti Dinar",  "KD") },
    "KYD" to { Currency("KYD", 136, 2, "Cayman Islands Dollar",  "$") },
    "KZT" to { Currency("KZT", 398, 2, "Tenge",  "₸") },
    "LAK" to { Currency("LAK", 418, 2, "Lao Kip",  "₭") },
    "LBP" to { Currency("LBP", 422, 2, "Lebanese Pound",  "£") },
    "LKR" to { Currency("LKR", 144, 2, "Sri Lanka Rupee",  "₨") },
    "LRD" to { Currency("LRD", 430, 2, "Liberian Dollar",  "$") },
    "LSL" to { Currency("LSL", 426, 2, "Loti",  "M") },
    "LYD" to { Currency("LYD", 434, 3, "Libyan Dinar",  "LD") },
    "MAD" to { Currency("MAD", 504, 2, "Moroccan Dirham",  "MAD") },
    "MDL" to { Currency("MDL", 498, 2, "Moldovan Leu",  "lei") },
    "MGA" to { Currency("MGA", 969, 2, "Malagasy Ariary",  "Ar") },
    "MKD" to { Currency("MKD", 807, 2, "Denar",  "ден") },
    "MMK" to { Currency("MMK", 104, 2, "Kyat",  "K") },
    "MNT" to { Currency("MNT", 496, 2, "Tugrik",  "₮") },
    "MOP" to { Currency("MOP", 446, 2, "Pataca",  "MOP$") },
    "MRU" to { Currency("MRU", 929, 2, "Ouguiya",  "UM") },
    "MUR" to { Currency("MUR", 480, 2, "Mauritius Rupee",  "₨") },
    "MVR" to { Currency("MVR", 462, 2, "Rufiyaa",  "Rf") },
    "MWK" to { Currency("MWK", 454, 2, "Malawian Kwacha",  "MK") },
    "MXN" to { Currency("MXN", 484, 2, "Mexican Peso",  "$") },
    "MXV" to { Currency("MXV", 979, 2, "Mexican Unidad de Inversion (UDI)",  "MXV") },
    "MYR" to { Currency("MYR", 458, 2, "Malaysian Ringgit",  "RM") },
    "MZN" to { Currency("MZN", 943, 2, "Mozambique Metical",  "MT") },
    "NAD" to { Currency("NAD", 516, 2, "Namibia Dollar",  "$") },
    "NGN" to { Currency("NGN", 566, 2, "Naira",  "₦") },
    "NIO" to { Currency("NIO", 558, 2, "Cordoba Oro",  "C$") },
    "NOK" to { Currency("NOK", 578, 2, "Norwegian Krone",  "kr") },
    "NPR" to { Currency("NPR", 524, 2, "Nepalese Rupee",  "₨") },
    "NZD" to { Currency("NZD", 554, 2, "New Zealand Dollar",  "$") },
    "OMR" to { Currency("OMR", 512, 3, "Omani Rial",  "﷼") },
    "PAB" to { Currency("PAB", 590, 2, "Balboa",  "B/.") },
    "PEN" to { Currency("PEN", 604, 2, "Sol", "S/.") },
    "PGK" to { Currency("PGK", 598, 2, "Kina",  "K") },
    "PHP" to { Currency("PHP", 608, 2, "Philippine Peso",  "₱") },
    "PKR" to { Currency("PKR", 586, 2, "Pakistan Rupee",  "₨") },
    "PLN" to { Currency("PLN", 985, 2, "Zloty",  "zł") },
    "PYG" to { Currency("PYG", 600, 0, "Guarani",  "Gs") },
    "QAR" to { Currency("QAR", 634, 2, "Qatari Riyal",  "﷼") },
    "RON" to { Currency("RON", 946, 2, "Romanian Leu", "lei") },
    "RSD" to { Currency("RSD", 941, 2, "Serbian Dinar", "RSD") },
    "RUB" to { Currency("RUB", 643, 2, "Russian Ruble", "₽") },
    "SAR" to { Currency("SAR", 682, 2, "Saudi Riyal", "﷼") },
    "SEK" to { Currency("SEK", 752, 2, "Swedish Krona", "kr") },
    "SGD" to { Currency("SGD", 702, 2, "Singapore Dollar", "$") },
    "SYP" to { Currency("SYP", 760, 2, "Syrian Pound", "£") },
    "THB" to { Currency("THB", 764, 2, "Baht", "฿") },
    "TND" to { Currency("TND", 788, 3, "Tunisian Dinar", "DT") },
    "TRY" to { Currency("TRY", 949, 2, "Turkish Lira", "₺") },
    "TTD" to { Currency("TTD", 780, 2, "Trinidad and Tobago Dollar", "TT$") },
    "TWD" to { Currency("TWD", 901, 2, "New Taiwan Dollar", "NT$") },
    "UAH" to { Currency("UAH", 980, 2, "Hryvnia", "₴") },
    "USD" to { Currency("USD", 840, 2, "US Dollar", "$") },
    "UYU" to { Currency("UYU", 858, 2, "Peso Uruguayo", "\$U") },
    "UZS" to { Currency("UZS", 860, 2, "Uzbekistan Sum", "so'm") },
    "VES" to { Currency("VES", 928, 2, "Bolívar Soberano", "Bs.S") },
    "VND" to { Currency("VND", 704, 0, "Dong", "₫") },
    "XCG" to { Currency("XCG", 532, 2, "Caribbean Guilder",  "Cg") },
    "YER" to { Currency("YER", 886, 2, "Yemeni Rial", "﷼") },
    "ZAR" to { Currency("ZAR", 710, 2, "Rand", "R") }
)
